SoC-2015-Ideas.md

Update builtin project proposal

---

rev_news/news_sources.md

Gather some ideas on how to produce content

---

rev_news/draft/edition-1.md

Add links and news

---

_includes/navbar.html

See: http://git.github.io/rev_news/rev_news.html

Fix wrong link to the about page

---

_includes/README.md
_posts/2015-03-25-edition-1.markdown
css/COPYING
css/main.css

I've grabbed some CSS from the libgit2 page, basically the same setup that they have on the git-scm.com page as well, and worked it into our site.
The layout is pretty much the same, but the colors and fonts are prettier, at least.
I also changed all the quotes in edition 1 to be blockquotes, because that's what they are. I did make them monospaced, so stuff from the mailing list still looks like monospaced mailing list text.
Please note that I hardly know anything about CSS, and now I know even more than I ever wanted to know. Or something.
@chriscool Please take a look.

Prettier design

---

rev_news/draft/edition-2.md

I did a quick pass rewording a couple of paragraphs. Feel free to discard if you want to maintain a single consistent voice.

Tiny fixes to wording of General section

---

rev_news/draft/edition-2.md

@chriscool as you suggested I added a small mention of John's talk.

Git lob mention

---

rev_news/draft/edition-2.md

It is not necessary to ask people to beat software, when the desired outcome is actually
to have people test the software. Using clear, positive language will help reinforce the
friendly, helpful behaviour I experienced at Git Merge.

Remove violent language; replace it with the desired action.

---

rev_news/rev_news.md

rev_news: fix some typos

---

rev_news/drafts/edition-4.md

rn-4: a few items for Releases section

---

_includes/navbar.html
_layouts/default.html
css/main.css

A shot at fixing issue: 43
https://github.com/git/git.github.io/issues/43

More responsive pages

---

css/main.css

width: 100% wasn't a good idé. width: auto works better.

Fixed a little bug on the navbar on small screens

---

rev_news/drafts/edition-5.md

Use permalinks for the Git for Windows RCs, add 2.4.5.1

---

rev_news/drafts/edition-5.md

This adds @sunshineco's article from:
http://thread.gmane.org/gmane.comp.version-control.git/273362/focus=273370
along with some changes to make it fit better with the rest.
Thanks a lot @sunshineco!

Git worktree article

---

rev_news/drafts/edition-5.md

@tfnico this is to improve the last links

rn-5: improve last links

---

rev_news/drafts/edition-6.md

This release seems interesting enough to add a bit more content in the edition.

Expand the section on the 2.5 release

---

rev_news/drafts/edition-8.md

Git Rev 8: mention v3 of the Travis patches

---

rev_news/drafts/edition-8.md

Disclaimer: This developer is working at Microsoft.

Git Rev 8: mention that VSO supports git-lfs now

---

rev_news/drafts/edition-8.md

Add discussion of ref backends

Toot my own horn

---

rev_news/drafts/edition-9.md

@chriscool Some of these paragraphs felt a bit clumsy, so I tried to improve them here. You like?

Improve wording in "file time issues" section

---

rev_news/drafts/edition-9.md

Following up to Christian's email, here are my answers to the questions (I added How did you start getting involved with Git?).

Interviewing myself

---

rev_news/drafts/edition-12.md

... (and Git for Windows releases as well).

Rev News 12: mention Git releases

---

SoC-2016-Microprojects.md

I went through the list of the microprojects, trying to weed out the ones that are already merged, and keeping the ones we can still use.  The commit message of the first commit contains a better description of what happened to all the microprojects (I hope I didn't miss anything).
The PR also adds one microproject coming from a mail by peff on the mailing list, and one more I thought of.
There's one more potential microproject that I found on the [mailing list](http://thread.gmane.org/gmane.comp.version-control.git/1452815916-6447-1-git-send-email-gitster@pobox.com), but there was already an implementation by [Moritz Neeb](http://thread.gmane.org/gmane.comp.version-control.git/56ACF82B.2030005@moritzneeb.de) and I didn't really look into it any deeper if that's already all the calls, or …

Microprojects

---

SoC-2016-Ideas.md
SoC-2016-Microprojects.md

Update the URL since we now have a more "normal" `master` branch and add the two main projects we'd be looking to mentor.
/cc @ethomson

libgit2 projects

---

Outreachy-2016-May.md

These are based on feedback from Marina Zhurakhinskaya, one of the program coordinators.

a few tweaks to the outreachy page

---

SoC-2016-Microprojects.md

I think it might be interesting to see if some students can come up with interesting microprojects by themselves given some broad instructions explaining how they could search for some microprojects.

SoC-2016-Microprojects: explain how to search for microprojects

---

rev_news/drafts/edition-14.md

Add a link to my blog post about Git for Windows 2.8

---

rev_news/drafts/edition-15.md

BitKeeper is now Open Source...

Rev News: mention the big BitKeeper news

---

rev_news/drafts/edition-15.md

This pull request includes a few grammar changes, typo fixes, and expansion of some examples to make them easier to follow.

Small fixes for edition 15

---

rev_news/drafts/edition-16.md

Rev News 16: mention the 2.8.x and 2.9.0-rcx releases

---

rev_news/drafts/edition-17.md

Rev News 17: mention the 2.9.[12] releases

---

rev_news/drafts/edition-17.md

Some light reading for the Rev News

---

rev_news/drafts/edition-17.md

Explain what "Making open source data more available" GitHub blog post is about. This should help readers decide if it is what they want to read.

Expand "Making open source data more available" entry

---

rev_news/drafts/edition-18.md

Mention the 'reedited' version of Pro Git (2nd ed)

---

rev_news/drafts/edition-18.md

Mention that Gmane closed down its web site

---

rev_news/drafts/edition-18.md

Rev News: Mention tig 2.2

---

rev_news/drafts/edition-18.md

Link "Version control: Effective use, issues and thoughts, from a gamedev perspective"
_NOTE: this is from 02 August 2016, if it matters_

Add light reading (VC for gamedev)

---

rev_news/drafts/edition-19.md

@tfnico what do you think about this?
Feel free to make changes and merge this PR anyway.

rn-19: thank you Nicola and call for help

---

rev_news/drafts/edition-19.md

Announce survey, provide some information.
Rebased, put before request for help.

Git User's Survey 2016

---

_layouts/default.html

Add RSS feed to the html head so that web browsers can expose the RSS feed directly.

Make web browsers aware of RSS feed

---

rev_news/drafts/edition-20.md

Rev News: mention Git/Git for Windows releases

---

SoC-2017-Ideas.md

In the first commit, I just copied the 2016 Ideas page and remove most of the ideas.
Feel free to add them back if you think they are interesting.
I also replaced gmane references with public-inbox. 
In the second commit I added some ideas that I had already posted on issue #188, and also one I copied from the 2014 ideas page.

Soc2017 ideas

---

rev_news/drafts/edition-21.md

First try, feel free to edit ...

Added Git Merge 2017 announcement draft.

---

rev_news/drafts/edition-21.md

Rev News: mention Git for Windows v2.11.0-rc1

---

rev_news/drafts/edition-23.md

This links to my blog post where I talk about the Windows-specific improvements in 2.11.

Rev News 23: add a link that should have been in #22

---

rev_news/drafts/edition-23.md

Rev News: mention Git for Windows v2.11.0(3)

---

rev_news/drafts/edition-23.md

A thread that started as support, and ended with a patch (namely _[Test failures when Git is built with libpcre and grep is built without it](https://public-inbox.org/git/58688C9F.4000605@adelielinux.org/)_)

rn-23: "Test failures when Git is built with libpcre and grep is built without it"

---

SoC-2017-Microprojects.md

Removes ideas which have been done before and add one new microproject.

microprojects 2017

---

SoC-2017-Ideas.md

Improve the ideas page by adding possible mentors based on the following mailing list thread:
https://public-inbox.org/git/vpq1svtstud.fsf@anie.imag.fr/

SoC-2017-Ideas: add possible mentors

---

rev_news/drafts/edition-24.md

Git Merge 2017, fixes for Contributor's Summit, few links

A few links for Git Rev News #24

---

rev_news/drafts/edition-25.md

Rev News: mention blog post about generating SHA-1 collisions

---

_posts/2017-02-22-edition-24.markdown

... assuming here that Ben has a nephew called "Bob"... ;-)

Rev News #24: mention Ben Peart, not his nephew

---

rev_news/drafts/edition-27.md

Rev News: mention Dugite, the node.js bindings for git

---

rev_news/drafts/edition-27.md

Rev News: add links for new Git, Git for Windows and tig releases

---

rev_news/drafts/edition-27.md

Add article in Light Reading section

---

rev_news/drafts/edition-28.md

Rev News: add two links talking about the massive Windows repository

---

rev_news/drafts/edition-28.md

Rev News: mention Git (for Windows) v2.13.1

---

rev_news/drafts/edition-29.md

Rev News: new Git and Git for Windows releases

---

rev_news/drafts/edition-29.md

- [Making a clutter-free git diff on Gettext translation files](https://medium.com/@rkz_io/making-a-clutter-free-git-diff-on-gettext-translation-files-9c0c1bb1d8aa)
- [Git Please: how to force push without being a jerk](https://medium.freecodecamp.org/git-please-a182f28efeb5)
- [Bash tips: easier git branch deleting](https://medium.com/@Gryff/bash-tips-easier-git-branch-deleting-d93da0f0acec)

rn-29: add a few links in "Light reading" subsection

---

rev_news/drafts/edition-33.md

A couple of links for RevNews

---

rev_news/drafts/edition-33.md

Some more Git-related news from Microsoft

---

rev_news/drafts/edition-33.md

It reflects a bit more what you can do with vimagit.

complete vimagit description

---

rev_news/drafts/edition-33.md

Maybe this end better reflects the conclusion of the discussion.

rn-33: change CRLF article end

---

rev_news/drafts/edition-34.md

I've added a section for watching and listening.
I've added a description of the two All Things Git episodes that were posted in november.
Thank you for the good work!

Add watching and listening section

---

rev_news/drafts/edition-34.md

In all "Various", "Light reading" and Git tools and sites" sections.

rn-34: Add a few links and tools

---

_posts/2017-11-22-edition-33.markdown

Propose small spelling change

---

rev_news/drafts/edition-36.md

One minor spelling correction:
1. The [FOSDEM](https://fosdem.org) conference was incorrectly spelled "FOSSDEM".
And two inclusions:
1. Add a link to a new GUI, [GitFinder](https://gitfinder.com/)
2. One episode of [All Things Git](https://allthingsgit.com/) for January.  (I hope that you don't mind the shameless self promotion!)

MInor updates

---

rev_news/drafts/edition-37.md

Rev News: some links related to the Git Merge conference

---

rev_news/drafts/edition-37.md

Rev News: add a link to the blog post about GVFS on Mac

---

rev_news/drafts/edition-37.md

Rev News: mention that v2.17.0-rc0 is available also for Windows

---

rev_news/drafts/edition-38.md

Some improvements for the interview.

rn-38: improvements for Jiang Xin's interview

---

rev_news/drafts/edition-39.md

RevNews: add a few interesting links

---

rev_news/drafts/edition-39.md

and Karki is pronounced as "Car Key" 😃

fix name typo

---

rev_news/drafts/edition-40.md

Expand on the purposes of the tools, and mention that these are being announced due to the recent presentation to the Git London User Group.

clarify purpose and context of git branch workflow tools

---

_posts/2018-06-20-edition-40.markdown

Ed's surname really has no 'p' in it: http://www.radiotfs.com/Show/141/ThereisNoPinThomson

RevNews: fix misspelled name

---

rev_news/drafts/edition-43.md

RevNews: add a link to the GitOps article on DZone

---

rev_news/drafts/edition-45.md

Very small typo in Edition 45

---

rev_news/drafts/edition-45.md

Add missing closing parenthesis, add missing space, and fix a link.

rn-45: a few small fixes

---

rev_news/drafts/edition-45.md

This version of article may need some trimming down in size.  I thing some things are a bit redundant.

rn-45: Add "[RFC] Generation Number v2" article

---

rev_news/drafts/edition-46.md

RevNews: mention v2.20.0

---

SoC-2019-Ideas.md

Signed-off-by: Thomas Gummerer <t.gummerer@gmail.com>

add GSoC project for stashing merge conflicts

---

SoC-2019-Ideas.md

@dscho convinced me privately that mentoring these projects by myself would be doable.  Add myself as potential mentor for them.

add Thomas as possible mentor for a couple of projects

---

rev_news/drafts/edition-50.md

Update edition-50.md with Gerrit releases

---

rev_news/drafts/edition-51.md

Adding a recent post (written by me, sorry for the shameless self-
promotion) about the sparse push algorithm.
Also fix a small typo.

Light reading: Git push blog post

---

rev_news/drafts/edition-54.md

I don't really know how long this can be. What kind of details may be interesting?
Any feedback welcome.

Proposition of subject for translated manpages in rev 54

---

rev_news/drafts/edition-54.md

A quick proofreading would be great.

edition 54: Developer Spotlight

---

rev_news/drafts/edition-55.md

Update edition-55.md: added notes to reading list

---

rev_news/drafts/edition-55.md

Fix spelling of James Ramsay

---

rev_news/drafts/edition-56.md

I noticed measured and acknowledged misspelled twice. Thought it would be nice practice to proofread and create a pull request. 
Signed-off-by: george espinoza <gespinoz2019@gmail.com>

edition-56.md: proofread four  words to help out

---

rev_news/drafts/edition-60.md

I've added the interview with Chris Webster with some minor fixes like correcting git -> Git etc.
One thing I'm not sure abuot is whether we have to explicitly mention that he is a contributor to GitGitGadget before the list of questions.

rn-60: add interview with Chris Webster

---

General-Application-Information.md

Improve on https://github.com/git/git.github.io/pull/414 that was merged prematurely.

General-Application: rephrase note about giving back

---

General-Application-Information.md

This is an update following https://github.com/git/git.github.io/pull/418 and https://github.com/git/git.github.io/pull/414
cc @sivaraam @tgummerer

General-Application: add quote about mentoring

---

SoC-2020-Ideas.md

Unfortunately the commit 6b5edec6557930888441c626f9272dc2be0c769e failed to build.
> The page build failed for the `master` branch with the following error:
>
> Unable to build page. Please try again later.
This pull request was created to examine, and if possible fix this issue.

SoC-2020-Ideas.md: add trailing empty lines to force rebuild

---

rev_news/drafts/edition-63.md

- Fix a typo
- Add more public-inbox links to discussions
- Add a bit of history

Update the story on the reviews of %(push:remoteref)

---

Hacking-Git.md

I made a Gist out of my debugging tips, linked to it and added a couple more links that I find relevant (including those mentioned in https://github.com/git/git.github.io/issues/439).
Tell me if I need to tweak some things.
/cc @chriscool @sivaraam

Add more links to Hacking Git

---

rev_news/drafts/edition-65.md

The first is a helpful article, complete with screencasts, that delves
into the power of a Git rebase workflow. The second is a link to the
Git Lint tool which supports the learnings documented in the Git Rebase
article.
- [Issue](https://github.com/git/git.github.io/issues/441) - This is the issue this was discussed in.
Added a link to [Git Lint](https://www.alchemists.io/projects/git-lint) as I thought that might be handy know about for the readership as well.

Added Git rebase article and lint tooling

---

rev_news/drafts/edition-65.md

I've added some links where I felt appropriate. One thing I'm not sure is if it would be nice to link "JGit" to https://www.eclipse.org/jgit/ or not.

rn-65: add interivew with Jonathan Tan

---

rev_news/drafts/edition-67.md

Per a suggestion from Christian Couder, I am adding a pull request to show my recent git related blog post.

rn-67: add link to Arista Networks' blog post

---

Outreachy-21-Microprojects.md

micro: unify semantics for -dirty suffix around submodules

---

rev_news/drafts/edition-67.md

See https://github.com/git/git.github.io/issues/455#issuecomment-683934103

Add a link to `git-in`

---

rev_news/drafts/edition-70.md

I've added a short news item for the sharness syntax mentioned by Christian in https://github.com/git/git.github.io/issues/468#issuecomment-741012684
I'm not sure if I placed it in the right place. So, feel free to shuffle/re-word it as necessary :)

rn-70: mention Felipe's Vim syntax file

---

General-Microproject-Information.md

Newcomers applying for an internship program might not be
aware of the commit message guidelines of our community.
So, linking to it from the "General Microproject Information"
might be helpful.

Point to information about writing a good commit message

---

General-Microproject-Information.md

Link to MyFirstContribution and Hacking-Git

---

_layouts/default.html

Made the setting in the default file. If this change fixes the old one, I'll delete the old one.

Change default.html

---

rev_news/drafts/edition-75.md

Saw this fun little post from @felipec and thought it would make a nice article.
I tried to do a little summary and add some comments around trailers I thought were interesting, but please feel free to add/change/suggest others.
@felipec as it was your post happy to defer to you if there was anything in particular you wanted to say or highlight.

rn-75: Add article "The top 1% of commit trailers"

---

rev_news/drafts/edition-76.md

Add reference and description for Interactive Git History site.

Update edition-76.md with git history site

---

Mentoring-Program-Guide.md

Hopefully such a guide can help participants in a GSoC or Outreachy, and their mentors too.

Add Mentoring-Program-Guide.md

---

rev_news/drafts/edition-81.md

Rev News: link to Stolee's and Lessley's newest talk

---

rev_news/drafts/edition-82.md

Minor typographical corrections to my Developer Profile

Update edition-82.md with minor corrections to Developer Profile

---

.gitignore
General-Application-Information.md

Noticed a possible sentence rephrase to the General Application Information which I've done.
Also, ignored the vendor directory that gets generated on running `bundle install`.

Some miscellaneous changes

---

rev_news/drafts/edition-84.md

I also added the YouTube video that quickly presents the new features. I hope that's OK!

Add Tower for Mac 8.0 to Releases

---

SoC-2022-Ideas.md

As discussed on the mailing list, added me as a possible mentor in `Unify ref-filter formats with other pretty formats`.
cc: @chriscool @sivaraam

SoC-2022-Ideas: add Hariom as possible mentor

---

SoC-2022-Ideas.md

As discussed\[1\] on the list, here is a description of a GSoC project
which takes a look at a handful of potential performance improvements
for reachability bitmaps.
Like my Outreachy proposal\[2\], there isn't one specific bitmap project,
but instead a handful of small- to medium-sized sub-projects that
students should feel free to choose from. This is by design to protect
against the case that one project doesn't carry the benefits we expect,
or a student changes their interest, etc.
\[1\]: https://lore.kernel.org/git/YfGpjm8mCkWIPM6V@nand.local/
\[2\]: https://www.outreachy.org/outreachy-december-2021-internship-round/communities/git/#improve-reachability-bitmaps
##
/cc @sivaraam, @chriscool

SoC-2022-Ideas.md: add "reachability bitmap improvements"

---

rev_news/drafts/edition-85.md

We released the 8.1 update to Tower today. I also published a new blog post, so here are 2 more additions to this month's newsletter, if you agree! :)

rn-85: Add Tower for Mac 8.1 release and one more "Light Reading" suggestion

---

rev_news/drafts/edition-86.md

Here are some "Light Reading" suggestions published this month on Tower's blog:
- Setting Up Git on Windows Subsystem for Linux
- How to Clean Up Fully Merged Feature Branches
I'm also including our "Mac Dev Survey Results" page for 2 reasons:
1. It covers some questions focused on Git, such as code hosting platforms or diff tools;
2. It includes some hilarious commit messages (in the "Not so serious" section).

rn-86: Add some "Light Reading" suggestions

---

rev_news/drafts/edition-86.md

Most likely some editing gone wrong

Proofreading

---

rev_news/drafts/edition-86.md

Links to light reading and a quite watchable tutorial with more
advanced topics than usual.
Signed-off-by: Philip Oakley <philipoakley@iee.email>

Can you read Code article, and the FreeCode camp tutorial tidbits

---

rev_news/drafts/edition-87.md

I added a new Tower release (v3.2 for Windows now supports Force Push with Lease).
I also added a Mastering Tower video/blog post, sharing a big collection of tips and tricks for the Tower Git client.

rn-87: Add new release + Light Reading suggestion

---

rev_news/drafts/edition-88.md

I added a new Tower for Mac release and 4 new blog posts 🙂

rn-88: Add new release + Reading suggestions

---

rev_news/drafts/edition-88.md

rn-88: fix link to the 'resh' tool repository

---

rev_news/drafts/edition-89.md

Addresses Jakub's comment in PR #590 [comment][1]
[1]: https://github.com/git/git.github.io/pull/590#issuecomment-1178067501

rn-89: mention the year and previous appearance of article

---

rev_news/drafts/edition-89.md

Kaartic, sorry for a late response. This is against the draft of edition 89

interview: gitster

---

rev_news/drafts/edition-92.md

Add articles suggested in the comments of edition #92: [ [comment 1](https://github.com/git/git.github.io/issues/602#issuecomment-1283919090) ] [ [comment 2](https://github.com/git/git.github.io/issues/602#issuecomment-1291012811) ].
I've linked to recent monorepo related blog that I could think of as relevant. Do suggest other ones in case they would be relevant.

Some more articles for edition #92

---

rev_news/drafts/edition-92.md

A minor fix which I noticed while reading the draft.

rn-92: add a missing word to complete a sentence

---

SoC-2023-Ideas.md

Both 'git grep' and 'git rm' were completed as part of GSoC last year. Update the list to reflect which commands are still available for the project.

SoC-2023-Ideas: remove finished sparse index integrations

---

rev_news/drafts/edition-103.md

I've added my conclusion following our usual structure. Kindly suggest any additions / corrections.
Note: I've used the pronoun "they" for Shuqi Liang as I'm unsure as to what pronouns should be used for them. It would be great it someone could clarify the same. I'll be happy to update the content. @vdye  @Cheskaqiqi ?

rn-103: add entry about conclusion of GSoC 2023

---

rev_news/drafts/edition-107.md

Just suggesting an article I recently wrote if you all think it's a good fit.

rn-107: Add git config article

---

rev_news/drafts/edition-108.md

Hello. :wave: I wanted to share some of the recent work I've been doing in the Git community which taps into Git commits, notes, and trailers to nice effect.

Added Git trailer and Milestoner links

---

SoC-2024-Ideas.md

We have two projects related to migrating of unit tests. Clarify the difference between them clearly.

SoC-2024: clarify distinction of first two projects

---

SoC-2024-Ideas.md

.. for the unit test migration project.

SoC-2024: include Kaartic Sivaraam as a co-mentor

---

rev_news/drafts/edition-108.md

Motivated by comments of Markus and Christian in the discussion of edition 108 [ref 1].
[ref 1]: https://github.com/git/git.github.io/issues/686#issuecomment-1971933785

rn-108: link to Dijkstra's article about goto

---

rev_news/drafts/edition-111.md

Addressed the following comment: https://github.com/git/git.github.io/issues/709#issuecomment-2110145273

rn-111: include info about Git Merge 2024

---

General-Microproject-Information.md

I admit that it was I who wrote the original of this section [*] but the use of verb "defend" here gives a wrong impression that it is a lot more adversarial exchange than it really is.  It is not like your opponents are trying to shoot down your proposal, against which you need to successfully defend.  It is more like the reviewers and the contributor together try to figure out a good solution to what the problem the proposal tries to solve.
And it takes _understanding_ from all sides what others are bringing to the discussion.  A better verb to use is "explain" to give others visibility into what you have in this paragraph.
[Reference]
* https://lore.kernel.org/git/xmqq8usx4pvh.fsf@gitster.dls.corp.google.com/

Microproject-Information: the review interaction is a cooperative process

---

rev_news/drafts/edition-119.md

rn-119: Link to Boost Your Git DX second update

---

SoC-2025-Ideas.md

Kindly check if this wording sounds fine @pks-t

SoC-2025: convey that we prefer ref consolidation work

---

rev_news/drafts/edition-120.md

(I will again be offline for most of the weekend so I can
only wish you the best of luck with the release of this
edition, and promise I'll have a look at the content added
henceforth beginning next week.)

rn-120: minor copy edit

---

Hacking-Git.md

Ref: https://lore.kernel.org/git/CAFySSZBgG3QyqEXSs3t4LzGYw1VJrHPx4gomT0zSsWcvQLezAQ@mail.gmail.com/

Hacking-Git: remove review club from the list of resources

---

rev_news/drafts/edition-125.md

@jnareb, @yaitskov what do you think about talking this tool here?

rn-125: add git-phoenix tool
