git/git.github.io

rev_news/draft/edition-1.md
http://git.github.io/rev_news/rev_news.html calls the list "Git
mailng list"; be consistent and welcoming to non developers.
=> revnews: Git mailing list is not only for developers

rev_news/draft/edition-1.md
The fact that the patch was reviewed by the maintainer does not add
much value to the section by itself. It is a different matter if it
were accompanied by a summary of value the review added to the
discussion, but otherwise it only makes the section longer without
adding much value ot the reader.
=> revnews: remove meaningless "X also reviewed"

rev_news/draft/edition-1.md
The oldest topic covered in the current writing is $gmane/264899
"log --graph --no-walk" from early March.  By being explicit about
the earliest date, set the expectation of readers to avoid possible
complaints e.g. "why isn't that topic that is a lot more interesting
covered here?"
=> revnews: be explicit about the date range

rev_news/draft/edition-1.md
Retitle the "Reviews & Support" section to "Discussions",
add "General" subsection next to "Reviews" and "Support",
and mention the discussion thread that resulted in the
creation of this newsletter.
=> revnews: mention the discussion on revnews itself

rev_news/draft/edition-1.md
My feeling reading the list is that the discussion leading to this rev news was actually initiated by David Kastrup's message, hence he should be the one to credit here (even though his message insisted more on the problem than on solutions).
=> Mention David Kastrup in "Promoting Git developers"

rev_news/draft/edition-1.md
I figure it is interesting to mention recent Git "core" releases, 
as well as in related projects (libgit2, jgit, etc).
PR for @chriscool, since it is a larger block of text.
=> revnews: mention some recent releases

_config.yml, rev_news/edition-1.md
This makes https://git.github.io/rev_news/ do something sensible (as opposed to giving a 404). An obvious alternative would be to just have an index page that links to the editions in reverse chronological order.
This `redirect_from` will need to be updated manually as new editions are published.
Fixes #34.
=> rev_news: redirect rev_news/ to current edition

rev_news/edition-1.md
The link text for tig 2.1 announcement has the version number transposed. Align it with the linked content.
=> rev news edition 1: fix typo in tig 2.1 link

rev_news/draft/edition-2.md
The underscore means *italic* in Markdown, and the GitHub Pages renderer interprets underscores even in the middle of terms as such. Let's fix the funny rendering by escaping the underscores.
=> edition-2: fix rendering of underscore

rev_news/news_sources.md
=> rn sources: vger list is not only for developers

rev_news/edition-2.md
In paraphrasing a quote in 3bfd3a01054d3448aefdc148c3bb5e7a579935de, we lost the original meaning. There weren't regressions in v2.3; the original was trying to say that we care about making sure we don't have regressions since v2.3. Hopefully this paraphrase makes that more clear.
/cc @gitster @emmajane
=> rev-news: fixup quote regarding regressions from Junio

_includes/README.md
All the concerned information is mentioned in both about and readme section now.
=> Remove line containing a reminder to copy information

rev_news/drafts/edition-4.md
It is not so important that the original was unsafe; the fact that it was fixed and now is safe
is more important, and encourage people to try it out.
=> rn-4: stress that submitGit is now safe to use

rev_news/drafts/edition-4.md
It is not like reformatted and reflowed patches are ignored by malice; heavy corruption makes them impossible to apply and hard to comment on.
=> Rephrase "corrupt patches cannot be applied"

rev_news/drafts/edition-4.md
I found the phrase "It's now safe to use" a little alarming :-)  so I tweaked the text, and also provided a link to the GitHub issues for feedback.
https://github.com/git/git.github.io/issues/63#issuecomment-106760390
=> Tweak submitGit entry to be more reassuring

rev_news/drafts/edition-5.md
We don't want to mislead reader who is only lightly skimming the text
or who doesn't read the entire article that "git checkout --to" is the
final form.
=> rn-5: make it clear that "git checkout --to" is not final

rev_news/drafts/edition-5.md
@tfnico and @moy what do you think about this?
Thanks!
=> rn-5: move Ensimag and GSoC student reports under 'General'

rev_news/drafts/edition-6.md
Actual linked post will go live the same day as edition 6.
=> Add 'Did you know' section to edition 6

rev_news/drafts/edition-7.md
This should eventually become a blog post on
http://google-opensource.blogspot.fr/.
Let's use Git Rev News both as a way to work together on the draft, and as an alternative publication mechanism: readers of Git Rev News may like the text, and may not read Google's blog.
=> first draft of text for GSoC wrap up.

_posts/2015-09-09-edition-7.markdown
The original link is „doubled“ (probably a copy-paste error), so that youtube isn’t able to parse the timing part and starts the video at the beginning. So let us:
- remove the repetition,
- remove the reference to the not used youtu.be link shortener,
- and, as much as we all like the metric system, `21m51s` is more readable as `1311`.
=> rn-7: fix partly broken link to youtube

SoC-2016-Microprojects.md
Markdown replaces `--` with &#8211;
So I have added backtics so as to allow easy copy-paste and avoid confusion to newcomers.
=> Fix `--` converting to &#8211;

SoC-2016-Ideas.md
GitHub's markdown seems to render this as one big jumble, rather than as a `<pre>`-formatted block.
I'm not really sure _why_, but dropping the indentation seems to fix it.
=> soc-2016-ideas: adjust markdown for "whitelist" example

Outreachy-2016-May.md
This is a program similar to GSoC, but which may increase the range of applicants we get (specifically it allows non-students, but the applicants must be from an under-represented group).
Logistics-wise, it reuses most of the existing resources we've developed for GSoC (and in fact, candidates may just end up applying via GSoC if they qualify there).
I'm planning to merge this right away, as we're already halfway through the Outreachy application period, and I want to get this up ASAP. But comments, corrections, and reverts are welcome. :)
=> add Outreachy page for May 2016

SoC-2016-Ideas.md
As it is now one of the easiest "convert script to builtin" project, maybe it is worth to make it have its own section close to the other bisect related projects.
=> SoC-2016-Ideas: add project to convert 'git-bisect.sh' to a builtin

SoC-2016-Microprojects.md
This is a small improvement to take care of @peff 's comment in https://github.com/git/git.github.io/pull/134
=> SoC-2016-Microprojects: warn about fixing a 'test_expect_failure'

SoC-2016-Ideas.md, SoC-2016-Microprojects.md
Too late for this year, but we have so many wrong applications, let's try to clarify them now so that we have a better template next year. What do you think?
(we can merge this right after the deadline)
=> Soc instructions

SoC-2016-Ideas.md
I am sending this for next year.
It feels more honest to say that we usually accept at most 2 students these days, than to suggest that we will accept at least 2 students.
=> SoC-2016-Ideas: tell that we accept at most 2 students

SoC-2014-Ideas.md, SoC-2014-Org-Application.md, SoC-2015-Ideas.md, SoC-2015-Org-Application.md, SoC-2016-Ideas.md, SoC-2016-Org-Application.md, _posts/2015-03-25-edition-1.markdown, _posts/2015-04-15-edition-2.markdown, _posts/2015-05-13-edition-3.markdown, _posts/2015-06-03-edition-4.markdown, _posts/2015-07-08-edition-5.markdown, _posts/2015-08-05-edition-6.markdown, _posts/2015-09-09-edition-7.markdown, _posts/2015-10-14-edition-8.markdown, _posts/2015-11-11-edition-9.markdown, _posts/2015-12-09-edition-10.markdown, _posts/2016-01-13-edition-11.markdown, _posts/2016-02-10-edition-12.markdown, _posts/2016-03-16-edition-13.markdown, _posts/2016-04-20-edition-14.markdown, _posts/2016-05-11-edition-15.markdown, feed.xml, rev_news/drafts/edition-16.md, rev_news/edition-1.md
Now that GitHub Pages can use https (and we'll be upgrading http requests to https), we can use https links everywhere to avoid the upgrade step.
This is a purely mechanical conversion.
I do wonder if some of these could be relative links (they are all referring to the git.github.io site itself), but here I've taken the most conservative route.
/cc @git/web
=> convert all internal links to https

rev_news/drafts/edition-16.md
Like in 2015 (https://git.github.io/rev_news/2015/07/08/edition-5/),
students from engineering school Ensimag contributed to Git.  This is
a small article to thank the community and to show what we did during
these 4 weeks.
We really wanted this article to be personal, so we wrote using
first-person pronouns.
It's quite long, so it could be moved to another part of the Rev News
and it's not really a "Discussion", so it doesn't really fit to the
first section.
=> Ensimag contributing to git

rev_news/drafts/edition-17.md
I think it makes the sentence easier to understand, especially to not native English speakers (there were "move" twice in a a single sentence, each with different meaning: move ~= change or action, and move ~= shift or push). This is not the only way of improving it.
=> Stylistic change, to avoid duplicated "move" in a sentence

rev_news/drafts/edition-18.md
https://www.theguardian.com/info/developer-blog/2016/jul/02/git-merge-2016
=> Add write-up of Git Merge 2016 by Roberto Tyley

_posts/2016-07-20-edition-17.markdown, rev_news/drafts/edition-18.md
A few of those old `rev_news.html` links made it through... (after  https://github.com/git/git.github.io/issues/157). Also using HTTPS for preference.
=> Fix broken `Git Rev News page` links in Git Rev news

rev_news/drafts/edition-18.md
Based on my replies to _"Draft of Git Rev News edition 18"_ thread:
* Message-Id: [9f3b254f-451e-4f6d-233c-7e995d8e369e@gmail.com](https://public-inbox.org/git/9f3b254f-451e-4f6d-233c-7e995d8e369e@gmail.com)
* Message-Id: [6b492c8c-2c75-9258-03dc-78346c98ff69@gmail.com](https://public-inbox.org/git/6b492c8c-2c75-9258-03dc-78346c98ff69@gmail.com)
as requested by Christian Couder
* Message-Id: [CAP8UFD24QpuOOh1b3LCbnuF-0TSJC7E34mjvqo3zdebb_spNxw@mail.gmail.com](https://public-inbox.org/git/CAP8UFD24QpuOOh1b3LCbnuF-0TSJC7E34mjvqo3zdebb_spNxw@mail.gmail.com)
=> Expand info about Gmane web interface shutting down

rev_news/drafts/edition-19.md
Minor issue: make 'at the bottom' link to the bottom of page, or rather the anchor for "Credits" header at bottom.
=> Link "see our emails" in help request

rev_news/drafts/edition-19.md
link to thread on Git mailing list, and to Linux Plumber Conference site (as last entry in top-level "Other News").
=> Git Miniconference at Plumbers

rev_news/drafts/edition-20.md
Just a reminder for those who have not answered yet.
The "Git User's Survey 2016" is to end at 20 October 2016... one day after Git Rev News edition 20 is planned to come out.
=> rn20: Git User's Survey 2016 ends soon

rev_news/drafts/edition-20.md
Add discussion about changing the default abbrev length and dealing with abbreviated SHA-1s.
I'm not sure if I put it in the correct place; though as it is in 'next' now, perhaps "Reviews" and not "General" subsection of "Discussions" is a good choice. Note also that URLs to commits might need cleanups.
Should I have added a byline?
=> rn20: Changing the default for "core.abbrev"?

rev_news/drafts/edition-20.md
Add an information from Dscho about the use of Scientist library to ensure that the patches making interactive rebase faster are in fact correct.
I'm not sure if the new information is well connected to the rest of it; as it is now, this point has actually two endings...
=> rn20: expand a but about Dscho's work on interactive rebase

rev_news/drafts/edition-20.md
Add description of discussion about Git no longer working with musl libc's regex implementation out of the box (without setting `NO_REGEX=1` in build configuration).
I'm not sure if it is worth including, but I think it might be interesting (the relying on POSIX issue, and no code is easier maintenance). Also, perhaps it could be in "Support" instead.
Might need style tuneups, and perhaps byline.
=> rn20: musl libc vs NO_REGEX / REG_STARTEND

rev_news/drafts/edition-20.md
Add description of discussion leading to git-log-compact project (originally proposed as `contrib/git-log-times` script).
This time with byline...
=> rn20: Discussion around git-log-compact

_includes/navbar.html
Currently "about" in navigation bar is a 404. This is a fix - now it renders `about.md` as expected.
=> Fix 404 on About in Navbar

rev_news/drafts/edition-21.md
Since we're mentioning Git Merge, it makes sense to mention the contributor's summit, too. I didn't put in a lot of details, as the linked email covers much more.
=> revnews 21: mention contributor's summit

SoC-2017-Ideas.md, SoC-2017-Microprojects.md
This is a mixed bag of typographical fixups, along with converting references to gmane to point to public-inbox instead. I only bothered with the 2017 pages, as the older ones are basically historical. We should perhaps consider removing them from the navigation bar on the side (we could also remove them completely, but perhaps people would want to refer to them? They'd always be available in the history, of course).
=> soc-2017 typographical fixups

SoC-2017-Ideas.md
As it looks like libgit2 people have not responded to emails we sent, we can assume that they don't want to participate to the SoC this year.
The mailing list thread is:
https://public-inbox.org/git/vpq1svtstud.fsf@anie.imag.fr/
=> SoC-2017-Ideas: remove libgit2

rev_news/drafts/edition-24.md
Git Merge 2017 was on February 2-3, 2017 in Brussels, Belgium.
Hopefully there would be more reports.
=> rn-24: Add a few links about Git Merge 2017 event

rev_news/drafts/edition-24.md
Turn spaces into tabs to avoid rendering two items as code.
=> rn-24: fix broken markdown bullet list

SoC-2017-Microprojects.md
As I said in the review of Kannan's attempt in https://public-inbox.org/git/xmqqtw882n08.fsf@gitster.mtv.corp.google.com/, this is not a suitable topic for a micro-project, as doing it in a "micro" way adds more problems than it solves, and doing it correctly (which Kannan's attempt is a step in the right direction) is way more than a "micro".
Let's remove this.
=> "Previous branch" is too big for microproject

rev_news/drafts/edition-28.md
Add link to the Gerrit User Summit 2017 (formerly GitTogether) registration page.
=> Gerrit User Summit 2017 registration link

_posts/2017-06-14-edition-28.markdown
Use `inline code` style to avoid turning '--' (double dash) in
description of long options into '–' (long dash) ligature in few
more places.  Balance backticks.
Add block of code formatting in more places, and provide explicit
programming language name for each code block.
Align start of line comments in code blocks.
=> rn-28: Add more places with inline code style - formatting fixes and improvements

rev_news/drafts/edition-36.md
Dave Borowitz is the Tech Leader of the Gerrit Code Review project
while Luca Milanesio is the Director of GerritForge and, recently,
elected in the maintainers list of the Gerrit Code Review project
by Shawn and Dave.
=> Update RevNews #36 with correction of titles

rev_news/drafts/edition-38.md
Notes form Stefan:
> See the branch bw/protocol-v2 which is in next, that allows for
> listing refs selectively as well as having a distinction for "end of
> list" and "I am done talking", such that proxies to be written can be
> done easier. (There is 0000 and 0001 end packets IIRC).
=> rn-38: add notes from Stefan Beller about protocol-v2

rev_news/drafts/edition-39.md
In regards to the story about optimizing writes to unchanged files:
1) The text noted that en/rename-directory-detection-reboot would be
merged to next soon (that's what the last cooking email said), but it
has since been merged to next..
2) It's worth noting that Junio found a bug with Linus' proposed "stupid
brute force" patch (namely that if a file involved in a rename has
dirty changes before a merge, those dirty changes could be overwritten
without warning to the user).
3) Finally, since there is a specific commit message that explains the
history of the can-we-skip-worktree-updates check and what fix was
used, link to it so the curious can dig more (without having to read
all the patches about directory rename detection).
=> Add a few details about optimizing writes to unchanged files

rev_news/drafts/edition-40.md
- Added Sourcetree links, currently at 2.7.6 for Mac and 2.5.5 for Windows
- Updated Bitbucket Server to version 5.11 and updated the release notes link to match
- Updated the text to "Bitbucket Server", instead of "Bitbucket", to make it more clear the link is for the behind-the-firewall version
=> RevNews: Update Atlassian links.

_posts/2018-06-20-edition-40.markdown
It has been made very clear from both Microsoft and GitHub that they announced an *agreement*. So the intent is there, but the acquisition is far from final, and therefore the companies are still independent of each other, and are still managed independently as long as the deal is closed.
We should not spread inaccurate news, so let's just state the facts correctly (otherwise this RevNews item could be misconstrued to be crafted to help competing companies by using that age-old despicable technique of spreading Fear, Uncertainty, and Doubt). There is no need to invent anything here, what I did was a slightly edited copy/paste from Satya's blog post.
=> RevNews: do not claim that the Microsoft/GitHub deal is final

rev_news/news_sources.md
The old link http://thechangelog.com/tagged/git/ now redirects to https://changelog.com/tagged/git, which is a 404 page. This PR updates it to the new URL format.
In addition, some lines were wrapped to make the code view (and diffs) more readable. Rendered text is not affected.
=> rev news sources: wrap long lines; fix broken link

_posts/2018-04-18-edition-38.markdown, _posts/2018-07-18-edition-41.markdown, _posts/2018-08-22-edition-42.markdown
The Gerrit Code Review project recently migrated its homepage from being hosted on googlesource.com and rendered by Gitiles, to being hosted on Firebase and rendered by Jekyll.
As a result of this migration, the homepage is still under the same domain, but the URLs for the release notes have changed. Instead of  being located at`/releases/$version.md` they are now located at `/$version.html`.
This PR changes the URLs accordingly, and also adds missing anchors for some of the maintenance releases, so that clicking on the link now takes the reader directly to the relevant section for that release.
=> Fix gerrit release note links

rev_news/drafts/edition-46.md
Pretty interesting node.js-based application serving Git repositories via `http` and `https`.
=> Rev News: mention Adobe's `git-server`

rev_news/drafts/edition-46.md
=> Rev News: add a link to the Git Advent Calendar

rev_news/drafts/edition-46.md
* Remove those super ugly `(1)` suffixes. Git for Windows *never* uses them in the announcements, except for `(2)`, `(3)` etc i.e. where really necessary.
* Add the -rc releases.
* Remove the v2.19.2 release. It was demoted to pre-release status, there is really absolutely no sense that we should advertise this version in RevNews *after* it was demoted.
=> RevNews: really improve the Git for Windows links

SoC-2019-Microprojects.md
This microproject was already solved at 60759ba ("credential-cache: use XDG_CACHE_HOME for socket", 2017-03-17).
This PR also removes all trailing spaces.
=> SoC-2019-Microprojects: remove "Move ~/.git-credential-cache to > ~/.cache/git"

SoC-2019-Ideas.md
This project depends on stash-in-c going to at least `next`.  I'm
going to send an updated version of the patch series tonight, but
I'm not very confident at this point that it's actually going to
make it to next before GSoC starts.  I'd rather take the project
away now, before applications actually open, and later
re-introduce it, than misleading a student.
---
I wish I didn't have to make this last minute change, however I think it's best not to propose a project that we're not sure at this point is available during summer.  I'd be more than happy to put it back onto the list once stash-in-c made it to `next`.
cc: @chriscool @telezhnaya
=> remove stash'ing merge conflicts project

SoC-2019-Ideas.md
When the text within the ` (tildes)  is split between two lines
it is not rendered as expected. To be precise the part that
comes in the second line isn't visible.
It's worth noting that this is not clear from the rendering
of the markdown by GitHub. But it's clear from the syntax
highlighting done by the editor in GitHub and the rendering
in the website (where this was first noted).
=> SoC-2019-Ideas: don't split text within the `s

SoC-2019-Ideas.md
Those are smaller projects, so that Git can accept students from a wider
audience (i.e. students who are not already familiar with C, or with
mailing list-centered project workflows). The downside is that this will
require more effort from the mentors than was common in past years. The
upside is that this will bring all the benefits of more inclusive
development.
=> SoC-2019-Ideas: add two more ideas

rev_news/drafts/edition-52.md
Git for Windows' versioning scheme _drops_ the `(1)` for the first version that is based on an upstream version. I have fixed this many times, and will hopefully not have to fix it many more times.
=> Rev News: fix the Git for Windows version

rev_news/drafts/edition-54.md
This introduction focuses on two things:
* Providing a simple example to give a flavor for git-filter-repo usage
* Compares to existing tools and explains why I created a new tool instead of extending others
But it also provides several links for folks that want to know more.
=> rn-54: add an introduction to git-filter-repo

rev_news/drafts/edition-54.md
Found a few small typos and errors.  The most embarrassing one was the sed command in the one example I gave was broken (serves me right for changing my real module name to 'my-module' and then not re-testing), but some of the documents I linked to had a few minor issues too, so I updated them and made this PR to link to the newer versions.
=> rn-54: update links to corrected docs, fix sed command

rev_news/drafts/edition-55.md
Hi, I recently gave a talk about Git internals and tips and tricks on Web Weekend Kathmandu, 2019.
This is an annual conference here in Nepal and I was invited as a speaker for the talk.
The video isn't available yet, so here's the link to my slides of the talk.
=> Add a link to a presentation given about Git at Web Weekend Kathmandu

rev_news/drafts/edition-57.md
Fixed a few obvious typos, and made the use of 'tri-state' consistent (vs 'tristate')
=> edition-57.md: small typo fixes

rev_news/drafts/edition-60.md
Technically, it is not a piece of _Git_ news per se, but IMO it is rather important for many Git users to be made aware of the deprecation (and soon, disabling) of the `ssh-rsa` keys.
=> RevNews: add an important heads-up for SSH users

General-Application-Information.md
Let's encourage GSoC students and Outreachy interns to contribute and to mentor.
=> General-Application: add note about giving back and mentoring

rev_news/drafts/edition-60.md
Add a note that `git difftool` was suggested as a way to get side-by-side
diff in Git.
=> rn-60: add note about suggestion of `git difftool` in interview

rev_news/drafts/edition-63.md
It's relatively old news by now (late February), but if other people are as behind on news because of COVID-19 as I am, they might appreciate the pointer, still.
=> RevNews: mention isomorphic-git v1.0.0

Hacking-Git.md
The link to "Launching gdb explanations in CodingGuidelines" does not
actually highlight the bullet point about launching GDB. Correct the
hash fragment so that the correct lines are highlighted.
=> Hacking-Git: highlight correct lines in CodingGuidelines

Hacking-Git.md
In c271b5d (Hacking-Git: highlight correct lines in CodingGuidelines,
2020-06-07), we fixed lines which are highlighted in the link to the
"Launching gdb explanations in CodingGuidelines" section. However, this
is liable to break in the future as the document is updated.
Hardcode that link to point to the v2.27.0 release of Git instead of the
latest 'master' so that the selected lines will never change.
Although this may potentially present stale information to readers, this
is mitigated by two things. First, I don't anticipate that the GDB
instructions are likely to change. Second, in the section above, there
is a link to the 'master' version of CodingGuidelines so users looking
for that will find a link to the "fresh" version.
=> Hacking-Git: use a known version for link

rev_news/drafts/edition-65.md
Here is my initial attempt at an article. Please let me know your thoughts and what can be improved.
The 'General' section seemed most appropriate as I referenced quite a few different posts to the mailing list thread to show how the discussion evolved.
I wasn't sure about quoting style that should be used, and I ended up using quote formatting for the main arguments to try and highlight them, in-lining other quotes where it seemed appropriate.
I wasn't entirely sure how to resolve the article, so any feedback on that would be great as well.
=> rn-65: add The history of `master` in git article

_posts/2020-09-24-edition-67.markdown
I noticed when I read Rev News that the wording could be better for one sentence, and that the link I added to my script should have followed the example of the preceding links by including a verb. So here I am fixing that.
=> rn-67: fix wording and grammar

rev_news/drafts/edition-69.md
Fixes issue in the link caught by @sivaraam [here](https://github.com/git/git.github.io/pull/465#issuecomment-728202495).
=> rn-69: fix link to 'Git before Github' article

css/main.css
A few cleanups, plus fixes for Linux systems, which don't have any of the fonts listed.
This basically adds Roboto Slab, and DejaVu Serif to the list of font-family, which makes it readable in Linux systems. Plus the fallback to sans-serif (we are not in 90s anymore).
I tested this in Arch Linux, Android 9, and Windows 10. Everything looks the same, except Arch Linux.
This fixes issue #469.
=> CSS font fixes

css/main.css
As @jnareb mentioned in issue #463, it should be possible to "move the left margin" so the navbar isn't squeezed.
However, conceptually what is actually being done is very different: the container wrapper is expanded to the full width of the window, then, the elements inside are justified to the center, this way the browser knows where to place the "left margin" (the left-most location where the navbar starts), but in order for the elements to not expand to the full width of the window, a max-width for the site container is necessary.
While on it, I adjusted the sizes of the navbar and the site containers, and removed some extra unnecessary padding.
=> css: improvements to "move the left margin"

rev_news/drafts/edition-71.md
Provides additional insight into different kinds of cloning, especially
when you only care about repository metadata.
- Resolves comment in [Issue 475](https://github.com/git/git.github.io/issues/475).
=> Added Git metadata cloning article link

SoC-2021-Ideas.md
The "\<format\>" in the project "Use ref-filter formats in `git cat-file`" is not visible [here](https://git.github.io/SoC-2021-Ideas/). 
This PR is to fix that issue.
=> SoC-2021-Ideas: wrap <format> with backquote

SoC-2021-Ideas.md
Plain links need to be wrapped in angle-brackets to be
hyperlinked in the rendered version of the page. So,
surround plain-links with angle-brackets to ensure
they're hyperlinked.
=> SoC-2021-Ideas: ensure plain links are hyperlinked

General-Microproject-Information.md
Linkify plain links in "General Microproject Information" to make sure its easier for students to access those links.
=> Ensure plain links are linkified

_posts/2021-04-30-edition-74.markdown
While reading the support article, I felt that linking to Elijah's
e-mail that tabularizes the behaviour for the revert,
cherry-pick commands in various cases would be useful.
So, adding a link to it.
=> rn-74: support: add a link to the mail that has the behaviour table

Hacking-Git.md
Libera Chat seems to be the go-to place for a lot of Git developers, and the last standup meeting happened there. Safe to say, new contributors are more likely to get their questions answered there.
Since there seems to be no way to directly link Libera's web chat to `#git-devel` directly, I have put a generic link over the text 'Libera Chat'. Users will have to manually type `#git-devel` in the webchat interface, but I suppose that should be obvious enough to not be worth mentioning.
=> Update IRC link to Libera Chat

Mentoring-Program-Guide.md
Add two spaces at the end of the numbered list, so that it does not all come on the same line. Makes it easier to scan, and formats it more closely to what I think the author intended.
=> Mentoring-Program-Guide: make lines break

index.md
Let's acknowledge that this website isn't an experiment anymore and that it contains information about Git Rev News and the Git project involvement in the GSoC and Outreachy mentoring programs.
=> index: make this website definitive

_includes/README.md
Let's try to avoid people using issues in this repo to discuss/report Git problems.
=> README: discourage Git bug reporting

Outreachy-23-Microprojects.md
New micro-project: Add --no-sort option for git-for-each-ref
I have implemented this function myself roughly. Since I am
based on my old patches:
https://lore.kernel.org/git/e68635cda515a9cd504c1d7366e9c353ab2adb2e.1629882532.git.gitgitgadget@gmail.com/
It won't be difficult. So it may be a good micro project for 
newcomers who want to participate in this year's Outreachy.
Thanks.
=> Add a new Outreachy-23 micro-project

rev_news/drafts/edition-83.md
It's likely better to spell out Git for Windows as not everyone
might immediately understand what Git4Win refers to.
=> rn-83: spell out Git for Windows

SoC-2021-Ideas.md, SoC-2022-Ideas.md, SoC-2022-Microprojects.md
The ideas document is mostly empty now. Ideas are yet to be gathered
from the community and added.
We also hide the SoC 2021 documents and Outreachy microproject documents
as they're stale now. The SoC 2021 org application isn't hidden as
we haven't applied for 2022 yet.
**Note**: I'm creating the ideas doc without any ideas to make it easy for others to open a PR, if necessary.
=> Add GSoC 2022 material and hide 2021 material

Mentoring-Program-Guide.md
I happened to give the mentoring guide a read and noted some things that could be improved. I've done changes for those which are tracked via this PR. Do take a look and let me know your thoughts.
One thing I wanted to note. There's the following line in the guide:
> As we think it's best that you decide on your own the best time to update your blog and send notifications, you should then also decide when it's best to have a chat with your mentors. 
But there doesn't appear to be any mention about students deciding their best time to update blog and send notifications before that. Would it be a good idea to mention that before in the section about "Regular updates" ?
=> Some mentoring guide updates

rev_news/archive.md
The current `About Rev News` link results in a 404.
Link direct to the git.github.io page.
Fixes one point in #545 
Signed-off-by: Philip Oakley philipoakley@iee.email
=> archive.md: Update `About Rev News` link

_includes/README.md
The git.github.io pages set out to be a website to help Git Developers.
Highlight the linkage to the Git Rev News pages to help new contributors
find the Rev News contributions particularly when the repo layout is
subtly different from  web pages.
Signed-off-by: Philip Oakley <philipoakley@iee.email>
=> add 'Rev News' note to the top level README page

SoC-2022-Ideas.md
As discussed on the mailing list, here is an idea for a student project.
cc: @vdye, @sivaraam
=> Soc-2022-Ideas: Sparse Index Integrations

_includes/README.md
While Peff is taking a break from Git, update the list of people with
admin-rights on git/git.github.io to reflect who is active and can grant
push access to interested contributors.
Closes: git/git.github.io#553
##
/cc @chriscool, @sivaraam
=> _includes/README.md: update current set of admins

rev_news/drafts/edition-85.md
I published [this article](https://hackernoon.com/how-to-really-use-git-10-rules-to-make-git-more-useful) on HackerNoon this week. I think it fits nicely in the "Light Reading" section 🙂
=> Add article to Light Reading section

_includes/README.md
The e-mail links in README render properly in GitHub's rendering of
the README file. In the deployed site they render as plain text, though.
Correct this by fixing the formatting of e-mail links such that they
render properly in the deployed site.
=> README: fix rendering of e-mail links in About page

General-Microproject-Information.md
Git has converted from using travis-ci to github actions in commit
https://github.com/git/git/commit/4a6e4b9602630d50eb9d630c721bb01df97049f9.
We also need to update the documentation for possible SoC candidates.
The instructions for GitHub actions were strongly influenced by commit
https://github.com/git/git/commit/f003a91f5c5695a44a94efe9171bc905fbfa27ce.
Signed-off-by: Plato Kiorpelidis <kioplato@gmail.com>
=> General-Microproject-Information: convert travis-ci to github actions

rev_news/drafts/edition-86.md
Sorry it's a bit last minute and I totally understand if it's too late for this month, but I just came across this article that shows an interesting use case for `git worktree` that I wasn't familiar with.
=> rn-86: add git worktree article to light reading

SoC-2022-Ideas.md
E-mails were wrapped in backticks which resulted in them rendering
as code snippets.
Tweak the e-mails so that they are rendered in a linkified manner.
This would help students to easily copy e-mails address (or) send
e-mails to potential mentors.
I'm creating this one as a PR as I'm kind of unsure of the reason the e-mails have been wrapped in codeblocks rather than being linkified. Does wrapping the e-mails in code block offer some kind of spam protection?
=> SoC-2022-Ideas: linkify email links

rev_news/drafts/edition-88.md
This article was mentioned in a mailing list thread. Junio hinted at including the article in Rev News in that thread. Ref: https://public-inbox.org/git/xmqqv8smqzg6.fsf@gitster.g/
=> rn-88: include article about vimdiff mergetool driver change

rev_news/drafts/edition-89.md
This came up on the mailing list and may have been missed by many.
I could have included a `git switch --detach v0.99~954` option for those
that have cloned git.git
Signed-off-by: Philip Oakley <philipoakley@iee.email>
=> Link to Junio's suggestion for reading about the Git Internals

rev_news/drafts/edition-91.md
Hey guys, adding our list of Tower releases and new blog posts to this edition — along with a couple of posts that were also suggested for the previous edition (#597) but didn't make it 🙂
=> rn-91: Add new Tower releases and Light Reading

SoC-2023-Ideas.md
Remove 'rev-parse', since it was already integrated with sparse index last year [1]. Additionally, reorder the list of commands to reflect the relative difficulty of sparse index integrations, taking into account both the additional work of adding sparse-checkout compatibility (if needed) and what has been made easier as a result of other commands' integrations.
[1] https://lore.kernel.org/git/69efe637a18786b289db79971e9e49137306b57c.1651005800.git.gitgitgadget@gmail.com
=> SoC 2023: update sparse index command list

SoC-2022-Microprojects.md
The original description is somewhat confusing, and has been the source of real-world confusion on the mailing list.
Let's clarify what we are trying to promote and avoid, as well as give some examples and background about our integration test suite.
(Note: I don't think we ever wrote any new microproject ideas for GSoC 2023, and ISTM that we are just reusing the ones from 2022. That's fine, and is the reason that I made these changes in the SoC-2022 file instead of creating a new one).
=> SoC-2022-Microprojects.md: clarify exit-code microproject

rev_news/drafts/edition-99.md
Not sure if this PR is still in time to mention it, but we've just shipped version 9.4 today 😉
=> rn-99: Add new Tower for Mac release (9.4)

rev_news/drafts/edition-100.md
I've added the information that I've been able to gather regarding the contributors to the upcoming edition.
@vdye If Shuqi is writing blogs about their GSoC experience, could you share a link to it?
=> rn-100: add information regarding selected GSoC 2023 contributors

rev_news/drafts/edition-100.md
Re: https://github.com/git/git.github.io/pull/648#issue-1761972141, added blog details as shared by @cheskaqiqi [on the mailing list](https://lore.kernel.org/git/20230619145342.5830-1-cheskaqiqi@gmail.com/). Also, fixed a typo (s/could/could be) in the entry on Kousik's blog.
=> Add Shuqi blog details & fix typo

rev_news/drafts/edition-103.md
Ref #660 for the upcoming edition.
If there’s an RSS reader that links are pulled from, my Git-related posts can be subscribed to at https://adamj.eu/tech/atom-git.xml .
I’ll be releasing my book “Boost Your Git DX” soon, probably before Rev News 104, so it would be nice to add it then.
Thanks 🙏
=> rn-103: Link to .gitkeep post

rev_news/drafts/edition-105.md
Add the news of the Eclipse's projects JGit/EGit migrated to GerritHub.io for preserving 14 years of review history.
Also amend the Gerrit Code Review v3.9.0 release which is still at the rc6 level.
=> Add Eclipse migration to GerritHub

SoC-2024-Ideas.md
This is a suggestion by Google.
The change right now renders as follows locally.
<details><summary>If we use simple markdown syntax for including an image, it renders as follows.</summary>
<p>
</p>
</details> 
I'm fine with either rendering. Feel free to share your thoughts. 🙂
=> SoC-2024: include the organization logo at a prominent place

SoC-2024-Microprojects.md
Link to the helpful email by Eric that would help distinguish valid and invalid conversions of "test -e"
=> SoC-2024-Microprojects: add reference to help distinguish valid conversions

GSoC-Participants.md
This file is being collected to gather the information about the participants that have contributed to Git via GSoC, an outreach program conducted by Google each year. This would serve as a helpful reference.
The intention is not to restrict gathering the information only for GSoC. We've started gather this with GSoC. We'll expand to also gather information of participants who've contributed via Outreachy.
Related issue: #671
=> GSoC-particpants: add file with  partial info about participants

_layouts/default.html, css/main.css, script/script.js
<h3>Key changes include:</h3>
1. **Improved Side Navbar:** Remove the bullets, doesn't shrink when open some tabs and make the selected tab item bold.
2. **Elimination of Horizontal Scrollbars:** Horizontal scrollbars are now hidden in specific tabs
3. **Tab Indicator:** Implemented a visual indicator in the navbar to clearly identify the currently opened tab.
**Before**
**After**
<h4>**In smaller screen size**</h4>
| Before | After |
|--------|-------|
| ![Before Image](https://github.com/git/git.github.io/assets/163371960/600aa081-3921-45ee-a884-cea7ffdbbe2a) | ![After Image](https://github.com/git/git.github.io/assets/163371960/01831e37-f175-465d-895b-928f4bc30cab) |
=> Enhanced Side Navbar Functionality 

rev_news/drafts/edition-116.md
I'm also overriding some previous edits, so perhaps some
explanation is in order:
1. 079a323e4a75 changed some 'open-source' to 'open source',
but not all and not consistently.  Standard English uses
dashed forms for adjectives and non-dashed forms for nouns;
follow that rule.
2. 079a323e4a75 changed "people's" to "peoples'", which is
not correct here (it would imply a number of ethnic groups
is meant, but that's not the case); restore the original.
(As an aside, personally I tend to leave the interviews
alone beyond obvious typos, as I consider the language
idiosyncrasies part of the glimpse into an interviewee's
personality.)
=> rn-116: minor copy edit

rev_news/drafts/edition-116.md
This article details how to use `git for-each-ref` in new and interesting ways (including the new `is-base` field).
I published this article earlier today so thought it might be of interest to folks here too.
=> Added Git For Each Ref article link

rev_news/drafts/edition-119.md
(Just a couple nits I see in the current draft;
unfortunately I'm going to be offline during the weekend, so
if you publish tomorrow as planned I'm unlikely to be able
to provide any further input this time. I'll have another
look when I come back. :-)
=> rn-119: minor copy edit

SoC-2025-Microprojects.md
Related thread: https://public-inbox.org/git/Z5d_XbPfQQBnwgQf@ArchLinux/T/#m966de0eab8f454b40677086cf41032116f72cce6
I've tried to incorporate the `-Wsign-compare` microproject idea and tweaked one of the existing idea to make it more beginner friendly. Do checkout and let me know your thoughts.
Patrick does suggest to move this over into Git's source tree itself. I'll get on to the same once I get an idea on what ideas we plan on keeping and removing. If it does look good, I could try to imitate the same for our other ideas.
=> SoC-2025: integrate microproject ideas

General-Microproject-Information.md
HI!
This PR replaces the occurrences of `[GSoC][PATCH]` and similar by `[GSoC PATCH]`.
This change is based on the discussion [here](https://lore.kernel.org/git/xmqqo6ygmdst.fsf@gitster.g/T/#m71ba37afb0791a52563abbd7aaa29f88ba289b75).
=> Microproject Info: replace [Mentoring][PATCH] by [Mentoring PATCH]

Hacking-Git.md
Git for Windows' wiki pages were migrated in https://github.com/git-for-windows/git-for-windows.github.io/pull/59.
=> Replace outdated links to Git for Windows' wiki

SoC-2025-Microprojects.md
From an ongoing discussion on the mailing list [1], it would be nice to add some notes to the 'Modernize a test script' microproject. Let's do that.
[1]: https://lore.kernel.org/all/CAPig+cRm+sc+Rk-4SuQ5CrPeZLG2Nzz9B7+6OZxCq7tV5mzmBA@mail.gmail.com/
=> microprojects: add notes for the 2025 microproject list

SoC-2025-Microprojects.md
The last note in the modernization test scripts is a little vague. Clarify it to be more clear about which modernization point it is referring to from the ones in the quoted email.
=> microprojects: clarify last note in modernization test scripts

GSoC-Participants.md
With GSoC 2025 approaching, adding GSoC 2024 participants will help new contributors understand their journey, making it easier for them to navigate the program and the project.
=> GSoC-participants: add GSoC 2024 participants to the list

General-Microproject-Information.md
A handful of minor tweaks to the Microproject information page that I think will improve the document. Kindly let me know if any specific change needs further tweaks. :-)
=> Some tweaks to the Microproject information

rev_news/drafts/edition-121.md
=> rn-121: minor copy edit

Hacking-Git.md, SoC-2019-Ideas.md, SoC-2020-Ideas.md, SoC-2024-Ideas.md
Since the documentation in git is changed from *.txt to *.adoc format. Update references to reflect that change.
=> Rename references from *.txt to *.adoc in documentation paths.

_posts/2015-08-05-edition-6.markdown, _posts/2017-12-20-edition-34.markdown, _posts/2018-07-18-edition-41.markdown, _posts/2018-08-22-edition-42.markdown, _posts/2018-11-21-edition-45.markdown, _posts/2019-06-28-edition-52.markdown, _posts/2023-10-31-edition-104.markdown, _posts/2024-04-30-edition-110.markdown, _posts/2024-10-31-edition-116.markdown, _posts/2024-12-31-edition-118.markdown
Since the documentation in git is changed from *.txt to *.adoc format. Update references in previous editions to reflect that change.
=> Rename references from *.txt to *.adoc in Rev News editions.

General-Microproject-Information.md
The CI instructions are only present for GitHub. Since GitLab CI is also supported, let's add some documentation there for GitLab.
=> Add CI instructions for GitLab

General-Application-Information.md, General-Microproject-Information.md
There have been discussions both between Git GSoC mentors among themselves and between all the GSoC mentors on the Google Summer of Code Mentors List (`google-summer-of-code-mentors-list@googlegroups.com`) about applicants using AI more and more. It seems related to a big increase in the number of spam proposals that Git and some other project have been receiving recently.
Let's try to address this issue by providing guidelines for using AI tools to mentoring program candidates.
The Conservancy also recently organized talks about the use of AI tools to develop open source software. I have tried to take this into account especially by adding a "Legal issues" section in the guidelines.
=> Add guidelines for using AI tools

rev_news/drafts/edition-124.md
As @leereilly suggested on https://github.com/git/git.github.io/issues/780#issuecomment-2988364164 it might be a good idea to mention that Git Merge 2025 speakers and schedule have been announced.
@leereilly, @jnareb please take a look.
=> rn-124: add links to Git Merge speakers and schedule

rev_news/drafts/edition-127.md
It's really nice to see the momentum, after git-scm.com has mostly languished for a decade. Let's accelerate that momentum even more by mentioning it in Rev News!
=> Mention the Persian ProGit translation and other exciting news about Git's home page
